name: Testing

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Environment Variable
        run: |
          echo "ðŸ•µï¸ Debugging ENV_VARIABLES_FILE_TEST"
          echo "${{ vars.ENV_VARIABLES_FILE_TEST }}" | head -c 200
          echo ""
          echo "ðŸ” Length of ENV_VARIABLES_FILE_TEST: ${#ENV_VARIABLES_FILE_TEST}"
        env:
          ENV_VARIABLES_FILE_TEST: ${{ vars.ENV_VARIABLES_FILE_TEST }}

      - name: Add Test Environment Variables
        run: |
          echo "ðŸ§ª Using TEST environment"
          printf "%s" "${{ vars.ENV_VARIABLES_FILE_TEST }}" > .env.production
          cat .env.production

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Unit Tests
        run: yarn test:ci

  e2e-test:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    needs: unit-test
    environment: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Environment Variable
        run: |
          echo "ðŸ•µï¸ Debugging ENV_VARIABLES_FILE_TEST"
          echo "${{ vars.ENV_VARIABLES_FILE_TEST }}" | head -c 200
          echo ""
          echo "ðŸ” Length of ENV_VARIABLES_FILE_TEST: ${#ENV_VARIABLES_FILE_TEST}"
        env:
          ENV_VARIABLES_FILE_TEST: ${{ vars.ENV_VARIABLES_FILE_TEST }}

      - name: Add Test Environment Variables
        run: |
          echo "ðŸ§ª Using TEST environment"
          printf "%s" "${{ vars.ENV_VARIABLES_FILE_TEST }}" > .env.production
          cat .env.production

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Install Cypress Binary
        run: yarn cypress install

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          build: yarn build
          start: yarn start
          wait-on: http://localhost:3000
          browser: chrome
